#!/usr/bin/env node
// Generates audio samples for each provider
// Usage: ./scripts/samples.ts
// Output: samples/<provider>.<ext>

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { providerMap } from "../src/voipi.ts";

const ROOT = new URL("..", import.meta.url).pathname;
const SAMPLES_DIR = join(ROOT, "samples");
const TEXT = "Hello! This is a sample generated by VoiPi.";

// Skip browser provider (requires DOM)
const PROVIDERS = ["macos", "piper", "edge-tts", "google-tts"] as const;

mkdirSync(SAMPLES_DIR, { recursive: true });

for (const name of PROVIDERS) {
  const factory = providerMap[name];
  if (!factory) continue;

  console.log(`[${name}] Synthesizing...`);
  try {
    const provider = await factory();
    const audio = await provider.toAudio(TEXT);
    const ext = (audio.ext || ".wav").replace(/^\.?/, ".");
    const outPath = join(SAMPLES_DIR, `${name}${ext}`);
    writeFileSync(outPath, audio.data);
    const duration = audio.duration ? ` (${audio.duration.toFixed(1)}s)` : "";
    console.log(`[${name}] Saved: samples/${name}${ext}${duration}`);
  } catch (error) {
    console.error(`[${name}] Failed: ${(error as Error).message}`);
  }
}

console.log("\nDone!");
