/** @type {Record<string, { label: string, voices: { id: string, label?: string }[] }>} */
export const providers = {
  auto: {
    label: "Auto",
    voices: [],
  },
  "edge-tts": {
    label: "Edge TTS",
    voices: [
      // en-US
      { id: "en-US-AriaNeural" },
      { id: "en-US-AvaNeural" },
      { id: "en-US-AvaMultilingualNeural" },
      { id: "en-US-AndrewNeural" },
      { id: "en-US-AndrewMultilingualNeural" },
      { id: "en-US-EmmaNeural" },
      { id: "en-US-EmmaMultilingualNeural" },
      { id: "en-US-BrianNeural" },
      { id: "en-US-BrianMultilingualNeural" },
      { id: "en-US-JennyNeural" },
      { id: "en-US-GuyNeural" },
      { id: "en-US-ChristopherNeural" },
      { id: "en-US-EricNeural" },
      { id: "en-US-MichelleNeural" },
      { id: "en-US-RogerNeural" },
      { id: "en-US-SteffanNeural" },
      { id: "en-US-AnaNeural" },
      // en-GB
      { id: "en-GB-LibbyNeural" },
      { id: "en-GB-MaisieNeural" },
      { id: "en-GB-RyanNeural" },
      { id: "en-GB-SoniaNeural" },
      { id: "en-GB-ThomasNeural" },
      // en-AU
      { id: "en-AU-NatashaNeural" },
      { id: "en-AU-WilliamMultilingualNeural" },
      // en-CA
      { id: "en-CA-ClaraNeural" },
      { id: "en-CA-LiamNeural" },
      // en-HK
      { id: "en-HK-SamNeural" },
      { id: "en-HK-YanNeural" },
      // en-IN
      { id: "en-IN-NeerjaNeural" },
      { id: "en-IN-NeerjaExpressiveNeural" },
      { id: "en-IN-PrabhatNeural" },
      // en-IE
      { id: "en-IE-ConnorNeural" },
      { id: "en-IE-EmilyNeural" },
      // en-KE
      { id: "en-KE-AsiliaNeural" },
      { id: "en-KE-ChilembaNeural" },
      // en-NZ
      { id: "en-NZ-MitchellNeural" },
      { id: "en-NZ-MollyNeural" },
      // en-NG
      { id: "en-NG-AbeoNeural" },
      { id: "en-NG-EzinneNeural" },
      // en-PH
      { id: "en-PH-JamesNeural" },
      { id: "en-PH-RosaNeural" },
      // en-SG
      { id: "en-SG-LunaNeural" },
      { id: "en-SG-WayneNeural" },
      // en-ZA
      { id: "en-ZA-LeahNeural" },
      { id: "en-ZA-LukeNeural" },
      // en-TZ
      { id: "en-TZ-ElimuNeural" },
      { id: "en-TZ-ImaniNeural" },
      // af-ZA
      { id: "af-ZA-AdriNeural" },
      { id: "af-ZA-WillemNeural" },
      // sq-AL
      { id: "sq-AL-AnilaNeural" },
      { id: "sq-AL-IlirNeural" },
      // am-ET
      { id: "am-ET-AmehaNeural" },
      { id: "am-ET-MekdesNeural" },
      // ar
      { id: "ar-DZ-AminaNeural" },
      { id: "ar-DZ-IsmaelNeural" },
      { id: "ar-BH-AliNeural" },
      { id: "ar-BH-LailaNeural" },
      { id: "ar-EG-SalmaNeural" },
      { id: "ar-EG-ShakirNeural" },
      { id: "ar-IQ-BasselNeural" },
      { id: "ar-IQ-RanaNeural" },
      { id: "ar-JO-SanaNeural" },
      { id: "ar-JO-TaimNeural" },
      { id: "ar-KW-FahedNeural" },
      { id: "ar-KW-NouraNeural" },
      { id: "ar-LB-LaylaNeural" },
      { id: "ar-LB-RamiNeural" },
      { id: "ar-LY-ImanNeural" },
      { id: "ar-LY-OmarNeural" },
      { id: "ar-MA-JamalNeural" },
      { id: "ar-MA-MounaNeural" },
      { id: "ar-OM-AbdullahNeural" },
      { id: "ar-OM-AyshaNeural" },
      { id: "ar-QA-AmalNeural" },
      { id: "ar-QA-MoazNeural" },
      { id: "ar-SA-HamedNeural" },
      { id: "ar-SA-ZariyahNeural" },
      { id: "ar-SY-AmanyNeural" },
      { id: "ar-SY-LaithNeural" },
      { id: "ar-TN-HediNeural" },
      { id: "ar-TN-ReemNeural" },
      { id: "ar-AE-FatimaNeural" },
      { id: "ar-AE-HamdanNeural" },
      { id: "ar-YE-MaryamNeural" },
      { id: "ar-YE-SalehNeural" },
      // az-AZ
      { id: "az-AZ-BabekNeural" },
      { id: "az-AZ-BanuNeural" },
      // bn
      { id: "bn-BD-NabanitaNeural" },
      { id: "bn-BD-PradeepNeural" },
      { id: "bn-IN-BashkarNeural" },
      { id: "bn-IN-TanishaaNeural" },
      // bs-BA
      { id: "bs-BA-GoranNeural" },
      { id: "bs-BA-VesnaNeural" },
      // bg-BG
      { id: "bg-BG-BorislavNeural" },
      { id: "bg-BG-KalinaNeural" },
      // my-MM
      { id: "my-MM-NilarNeural" },
      { id: "my-MM-ThihaNeural" },
      // ca-ES
      { id: "ca-ES-EnricNeural" },
      { id: "ca-ES-JoanaNeural" },
      // zh
      { id: "zh-CN-XiaoxiaoNeural" },
      { id: "zh-CN-XiaoyiNeural" },
      { id: "zh-CN-YunjianNeural" },
      { id: "zh-CN-YunxiNeural" },
      { id: "zh-CN-YunxiaNeural" },
      { id: "zh-CN-YunyangNeural" },
      { id: "zh-CN-liaoning-XiaobeiNeural" },
      { id: "zh-CN-shaanxi-XiaoniNeural" },
      { id: "zh-HK-HiuGaaiNeural" },
      { id: "zh-HK-HiuMaanNeural" },
      { id: "zh-HK-WanLungNeural" },
      { id: "zh-TW-HsiaoChenNeural" },
      { id: "zh-TW-HsiaoYuNeural" },
      { id: "zh-TW-YunJheNeural" },
      // hr-HR
      { id: "hr-HR-GabrijelaNeural" },
      { id: "hr-HR-SreckoNeural" },
      // cs-CZ
      { id: "cs-CZ-AntoninNeural" },
      { id: "cs-CZ-VlastaNeural" },
      // da-DK
      { id: "da-DK-ChristelNeural" },
      { id: "da-DK-JeppeNeural" },
      // nl
      { id: "nl-BE-ArnaudNeural" },
      { id: "nl-BE-DenaNeural" },
      { id: "nl-NL-ColetteNeural" },
      { id: "nl-NL-FennaNeural" },
      { id: "nl-NL-MaartenNeural" },
      // et-EE
      { id: "et-EE-AnuNeural" },
      { id: "et-EE-KertNeural" },
      // fil-PH
      { id: "fil-PH-AngeloNeural" },
      { id: "fil-PH-BlessicaNeural" },
      // fi-FI
      { id: "fi-FI-HarriNeural" },
      { id: "fi-FI-NooraNeural" },
      // fr
      { id: "fr-BE-CharlineNeural" },
      { id: "fr-BE-GerardNeural" },
      { id: "fr-CA-AntoineNeural" },
      { id: "fr-CA-JeanNeural" },
      { id: "fr-CA-SylvieNeural" },
      { id: "fr-CA-ThierryNeural" },
      { id: "fr-CH-ArianeNeural" },
      { id: "fr-CH-FabriceNeural" },
      { id: "fr-FR-DeniseNeural" },
      { id: "fr-FR-EloiseNeural" },
      { id: "fr-FR-HenriNeural" },
      { id: "fr-FR-RemyMultilingualNeural" },
      { id: "fr-FR-VivienneMultilingualNeural" },
      // gl-ES
      { id: "gl-ES-RoiNeural" },
      { id: "gl-ES-SabelaNeural" },
      // ka-GE
      { id: "ka-GE-EkaNeural" },
      { id: "ka-GE-GiorgiNeural" },
      // de
      { id: "de-AT-IngridNeural" },
      { id: "de-AT-JonasNeural" },
      { id: "de-CH-JanNeural" },
      { id: "de-CH-LeniNeural" },
      { id: "de-DE-AmalaNeural" },
      { id: "de-DE-ConradNeural" },
      { id: "de-DE-FlorianMultilingualNeural" },
      { id: "de-DE-KatjaNeural" },
      { id: "de-DE-KillianNeural" },
      { id: "de-DE-SeraphinaMultilingualNeural" },
      // el-GR
      { id: "el-GR-AthinaNeural" },
      { id: "el-GR-NestorasNeural" },
      // gu-IN
      { id: "gu-IN-DhwaniNeural" },
      { id: "gu-IN-NiranjanNeural" },
      // he-IL
      { id: "he-IL-AvriNeural" },
      { id: "he-IL-HilaNeural" },
      // hi-IN
      { id: "hi-IN-MadhurNeural" },
      { id: "hi-IN-SwaraNeural" },
      // hu-HU
      { id: "hu-HU-NoemiNeural" },
      { id: "hu-HU-TamasNeural" },
      // is-IS
      { id: "is-IS-GudrunNeural" },
      { id: "is-IS-GunnarNeural" },
      // id-ID
      { id: "id-ID-ArdiNeural" },
      { id: "id-ID-GadisNeural" },
      // iu
      { id: "iu-Cans-CA-SiqiniqNeural" },
      { id: "iu-Cans-CA-TaqqiqNeural" },
      { id: "iu-Latn-CA-SiqiniqNeural" },
      { id: "iu-Latn-CA-TaqqiqNeural" },
      // ga-IE
      { id: "ga-IE-ColmNeural" },
      { id: "ga-IE-OrlaNeural" },
      // it-IT
      { id: "it-IT-DiegoNeural" },
      { id: "it-IT-ElsaNeural" },
      { id: "it-IT-GiuseppeMultilingualNeural" },
      { id: "it-IT-IsabellaNeural" },
      // ja-JP
      { id: "ja-JP-KeitaNeural" },
      { id: "ja-JP-NanamiNeural" },
      // jv-ID
      { id: "jv-ID-DimasNeural" },
      { id: "jv-ID-SitiNeural" },
      // kn-IN
      { id: "kn-IN-GaganNeural" },
      { id: "kn-IN-SapnaNeural" },
      // kk-KZ
      { id: "kk-KZ-AigulNeural" },
      { id: "kk-KZ-DauletNeural" },
      // km-KH
      { id: "km-KH-PisethNeural" },
      { id: "km-KH-SreymomNeural" },
      // ko-KR
      { id: "ko-KR-HyunsuMultilingualNeural" },
      { id: "ko-KR-InJoonNeural" },
      { id: "ko-KR-SunHiNeural" },
      // lo-LA
      { id: "lo-LA-ChanthavongNeural" },
      { id: "lo-LA-KeomanyNeural" },
      // lv-LV
      { id: "lv-LV-EveritaNeural" },
      { id: "lv-LV-NilsNeural" },
      // lt-LT
      { id: "lt-LT-LeonasNeural" },
      { id: "lt-LT-OnaNeural" },
      // mk-MK
      { id: "mk-MK-AleksandarNeural" },
      { id: "mk-MK-MarijaNeural" },
      // ms-MY
      { id: "ms-MY-OsmanNeural" },
      { id: "ms-MY-YasminNeural" },
      // ml-IN
      { id: "ml-IN-MidhunNeural" },
      { id: "ml-IN-SobhanaNeural" },
      // mt-MT
      { id: "mt-MT-GraceNeural" },
      { id: "mt-MT-JosephNeural" },
      // mr-IN
      { id: "mr-IN-AarohiNeural" },
      { id: "mr-IN-ManoharNeural" },
      // mn-MN
      { id: "mn-MN-BataaNeural" },
      { id: "mn-MN-YesuiNeural" },
      // ne-NP
      { id: "ne-NP-HemkalaNeural" },
      { id: "ne-NP-SagarNeural" },
      // nb-NO
      { id: "nb-NO-FinnNeural" },
      { id: "nb-NO-PernilleNeural" },
      // ps-AF
      { id: "ps-AF-GulNawazNeural" },
      { id: "ps-AF-LatifaNeural" },
      // fa-IR
      { id: "fa-IR-DilaraNeural" },
      { id: "fa-IR-FaridNeural" },
      // pl-PL
      { id: "pl-PL-MarekNeural" },
      { id: "pl-PL-ZofiaNeural" },
      // pt
      { id: "pt-BR-AntonioNeural" },
      { id: "pt-BR-FranciscaNeural" },
      { id: "pt-BR-ThalitaMultilingualNeural" },
      { id: "pt-PT-DuarteNeural" },
      { id: "pt-PT-RaquelNeural" },
      // ro-RO
      { id: "ro-RO-AlinaNeural" },
      { id: "ro-RO-EmilNeural" },
      // ru-RU
      { id: "ru-RU-DmitryNeural" },
      { id: "ru-RU-SvetlanaNeural" },
      // sr-RS
      { id: "sr-RS-NicholasNeural" },
      { id: "sr-RS-SophieNeural" },
      // si-LK
      { id: "si-LK-SameeraNeural" },
      { id: "si-LK-ThiliniNeural" },
      // sk-SK
      { id: "sk-SK-LukasNeural" },
      { id: "sk-SK-ViktoriaNeural" },
      // sl-SI
      { id: "sl-SI-PetraNeural" },
      { id: "sl-SI-RokNeural" },
      // so-SO
      { id: "so-SO-MuuseNeural" },
      { id: "so-SO-UbaxNeural" },
      // es
      { id: "es-AR-ElenaNeural" },
      { id: "es-AR-TomasNeural" },
      { id: "es-BO-MarceloNeural" },
      { id: "es-BO-SofiaNeural" },
      { id: "es-CL-CatalinaNeural" },
      { id: "es-CL-LorenzoNeural" },
      { id: "es-CO-GonzaloNeural" },
      { id: "es-CO-SalomeNeural" },
      { id: "es-CR-JuanNeural" },
      { id: "es-CR-MariaNeural" },
      { id: "es-CU-BelkysNeural" },
      { id: "es-CU-ManuelNeural" },
      { id: "es-DO-EmilioNeural" },
      { id: "es-DO-RamonaNeural" },
      { id: "es-EC-AndreaNeural" },
      { id: "es-EC-LuisNeural" },
      { id: "es-ES-AlvaroNeural" },
      { id: "es-ES-ElviraNeural" },
      { id: "es-ES-XimenaNeural" },
      { id: "es-GQ-JavierNeural" },
      { id: "es-GQ-TeresaNeural" },
      { id: "es-GT-AndresNeural" },
      { id: "es-GT-MartaNeural" },
      { id: "es-HN-CarlosNeural" },
      { id: "es-HN-KarlaNeural" },
      { id: "es-MX-DaliaNeural" },
      { id: "es-MX-JorgeNeural" },
      { id: "es-NI-FedericoNeural" },
      { id: "es-NI-YolandaNeural" },
      { id: "es-PA-MargaritaNeural" },
      { id: "es-PA-RobertoNeural" },
      { id: "es-PE-AlexNeural" },
      { id: "es-PE-CamilaNeural" },
      { id: "es-PR-KarinaNeural" },
      { id: "es-PR-VictorNeural" },
      { id: "es-PY-MarioNeural" },
      { id: "es-PY-TaniaNeural" },
      { id: "es-SV-LorenaNeural" },
      { id: "es-SV-RodrigoNeural" },
      { id: "es-US-AlonsoNeural" },
      { id: "es-US-PalomaNeural" },
      { id: "es-UY-MateoNeural" },
      { id: "es-UY-ValentinaNeural" },
      { id: "es-VE-PaolaNeural" },
      { id: "es-VE-SebastianNeural" },
      // su-ID
      { id: "su-ID-JajangNeural" },
      { id: "su-ID-TutiNeural" },
      // sw
      { id: "sw-KE-RafikiNeural" },
      { id: "sw-KE-ZuriNeural" },
      { id: "sw-TZ-DaudiNeural" },
      { id: "sw-TZ-RehemaNeural" },
      // sv-SE
      { id: "sv-SE-MattiasNeural" },
      { id: "sv-SE-SofieNeural" },
      // ta
      { id: "ta-IN-PallaviNeural" },
      { id: "ta-IN-ValluvarNeural" },
      { id: "ta-LK-KumarNeural" },
      { id: "ta-LK-SaranyaNeural" },
      { id: "ta-MY-KaniNeural" },
      { id: "ta-MY-SuryaNeural" },
      { id: "ta-SG-AnbuNeural" },
      { id: "ta-SG-VenbaNeural" },
      // te-IN
      { id: "te-IN-MohanNeural" },
      { id: "te-IN-ShrutiNeural" },
      // th-TH
      { id: "th-TH-NiwatNeural" },
      { id: "th-TH-PremwadeeNeural" },
      // tr-TR
      { id: "tr-TR-AhmetNeural" },
      { id: "tr-TR-EmelNeural" },
      // uk-UA
      { id: "uk-UA-OstapNeural" },
      { id: "uk-UA-PolinaNeural" },
      // ur
      { id: "ur-IN-GulNeural" },
      { id: "ur-IN-SalmanNeural" },
      { id: "ur-PK-AsadNeural" },
      { id: "ur-PK-UzmaNeural" },
      // uz-UZ
      { id: "uz-UZ-MadinaNeural" },
      { id: "uz-UZ-SardorNeural" },
      // vi-VN
      { id: "vi-VN-HoaiMyNeural" },
      { id: "vi-VN-NamMinhNeural" },
      // cy-GB
      { id: "cy-GB-AledNeural" },
      { id: "cy-GB-NiaNeural" },
      // zu-ZA
      { id: "zu-ZA-ThandoNeural" },
      { id: "zu-ZA-ThembaNeural" },
    ],
  },
  "google-tts": {
    label: "Google TTS",
    voices: [
      { id: "af" },
      { id: "ar" },
      { id: "bg" },
      { id: "bn" },
      { id: "bs" },
      { id: "ca" },
      { id: "cs" },
      { id: "da" },
      { id: "de" },
      { id: "el" },
      { id: "en" },
      { id: "es" },
      { id: "et" },
      { id: "fi" },
      { id: "fr" },
      { id: "gu" },
      { id: "hi" },
      { id: "hr" },
      { id: "hu" },
      { id: "id" },
      { id: "is" },
      { id: "it" },
      { id: "ja" },
      { id: "jw" },
      { id: "km" },
      { id: "kn" },
      { id: "ko" },
      { id: "la" },
      { id: "lv" },
      { id: "ml" },
      { id: "mr" },
      { id: "ms" },
      { id: "my" },
      { id: "ne" },
      { id: "nl" },
      { id: "no" },
      { id: "pl" },
      { id: "pt" },
      { id: "ro" },
      { id: "ru" },
      { id: "si" },
      { id: "sk" },
      { id: "sq" },
      { id: "sr" },
      { id: "su" },
      { id: "sv" },
      { id: "sw" },
      { id: "ta" },
      { id: "te" },
      { id: "th" },
      { id: "tl" },
      { id: "tr" },
      { id: "uk" },
      { id: "ur" },
      { id: "vi" },
      { id: "zh-CN" },
      { id: "zh-TW" },
    ],
  },
  piper: {
    label: "Piper",
    voices: [
      { id: "ar_JO-kareem-low" },
      { id: "ar_JO-kareem-medium" },
      { id: "bg_BG-dimitar-medium" },
      { id: "ca_ES-upc_ona-medium" },
      { id: "ca_ES-upc_ona-x_low" },
      { id: "ca_ES-upc_pau-x_low" },
      { id: "cs_CZ-jirka-low" },
      { id: "cs_CZ-jirka-medium" },
      { id: "cy_GB-bu_tts-medium" },
      { id: "cy_GB-gwryw_gogleddol-medium" },
      { id: "da_DK-talesyntese-medium" },
      { id: "de_DE-eva_k-x_low" },
      { id: "de_DE-karlsson-low" },
      { id: "de_DE-kerstin-low" },
      { id: "de_DE-mls-medium" },
      { id: "de_DE-pavoque-low" },
      { id: "de_DE-ramona-low" },
      { id: "de_DE-thorsten-high" },
      { id: "de_DE-thorsten-low" },
      { id: "de_DE-thorsten-medium" },
      { id: "de_DE-thorsten_emotional-medium" },
      { id: "el_GR-rapunzelina-low" },
      { id: "el_GR-rapunzelina-medium" },
      { id: "en_GB-alan-low" },
      { id: "en_GB-alan-medium" },
      { id: "en_GB-alba-medium" },
      { id: "en_GB-aru-medium" },
      { id: "en_GB-cori-high" },
      { id: "en_GB-cori-medium" },
      { id: "en_GB-jenny_dioco-medium" },
      { id: "en_GB-northern_english_male-medium" },
      { id: "en_GB-semaine-medium" },
      { id: "en_GB-southern_english_female-low" },
      { id: "en_GB-vctk-medium" },
      { id: "en_US-amy-low" },
      { id: "en_US-amy-medium" },
      { id: "en_US-arctic-medium" },
      { id: "en_US-bryce-medium" },
      { id: "en_US-danny-low" },
      { id: "en_US-hfc_female-medium" },
      { id: "en_US-hfc_male-medium" },
      { id: "en_US-joe-medium" },
      { id: "en_US-john-medium" },
      { id: "en_US-kathleen-low" },
      { id: "en_US-kristin-medium" },
      { id: "en_US-kusal-medium" },
      { id: "en_US-l2arctic-medium" },
      { id: "en_US-lessac-high" },
      { id: "en_US-lessac-low" },
      { id: "en_US-lessac-medium" },
      { id: "en_US-libritts-high" },
      { id: "en_US-libritts_r-medium" },
      { id: "en_US-ljspeech-high" },
      { id: "en_US-ljspeech-medium" },
      { id: "en_US-norman-medium" },
      { id: "en_US-reza_ibrahim-medium" },
      { id: "en_US-ryan-high" },
      { id: "en_US-ryan-low" },
      { id: "en_US-ryan-medium" },
      { id: "en_US-sam-medium" },
      { id: "es_AR-daniela-high" },
      { id: "es_ES-carlfm-x_low" },
      { id: "es_ES-davefx-medium" },
      { id: "es_ES-mls_10246-low" },
      { id: "es_ES-mls_9972-low" },
      { id: "es_ES-sharvard-medium" },
      { id: "es_MX-ald-medium" },
      { id: "es_MX-claude-high" },
      { id: "fa_IR-amir-medium" },
      { id: "fa_IR-ganji-medium" },
      { id: "fa_IR-ganji_adabi-medium" },
      { id: "fa_IR-gyro-medium" },
      { id: "fa_IR-reza_ibrahim-medium" },
      { id: "fi_FI-harri-low" },
      { id: "fi_FI-harri-medium" },
      { id: "fr_FR-gilles-low" },
      { id: "fr_FR-mls-medium" },
      { id: "fr_FR-mls_1840-low" },
      { id: "fr_FR-siwis-low" },
      { id: "fr_FR-siwis-medium" },
      { id: "fr_FR-tom-medium" },
      { id: "fr_FR-upmc-medium" },
      { id: "hi_IN-pratham-medium" },
      { id: "hi_IN-priyamvada-medium" },
      { id: "hi_IN-rohan-medium" },
      { id: "hu_HU-anna-medium" },
      { id: "hu_HU-berta-medium" },
      { id: "hu_HU-imre-medium" },
      { id: "id_ID-news_tts-medium" },
      { id: "is_IS-bui-medium" },
      { id: "is_IS-salka-medium" },
      { id: "is_IS-steinn-medium" },
      { id: "is_IS-ugla-medium" },
      { id: "it_IT-paola-medium" },
      { id: "it_IT-riccardo-x_low" },
      { id: "ka_GE-natia-medium" },
      { id: "kk_KZ-iseke-x_low" },
      { id: "kk_KZ-issai-high" },
      { id: "kk_KZ-raya-x_low" },
      { id: "lb_LU-marylux-medium" },
      { id: "lv_LV-aivars-medium" },
      { id: "ml_IN-arjun-medium" },
      { id: "ml_IN-meera-medium" },
      { id: "ne_NP-chitwan-medium" },
      { id: "ne_NP-google-medium" },
      { id: "ne_NP-google-x_low" },
      { id: "nl_BE-nathalie-medium" },
      { id: "nl_BE-nathalie-x_low" },
      { id: "nl_BE-rdh-medium" },
      { id: "nl_BE-rdh-x_low" },
      { id: "nl_NL-alex-medium" },
      { id: "nl_NL-mls-medium" },
      { id: "nl_NL-mls_5809-low" },
      { id: "nl_NL-mls_7432-low" },
      { id: "nl_NL-pim-medium" },
      { id: "nl_NL-ronnie-medium" },
      { id: "no_NO-nvcc-medium" },
      { id: "no_NO-talesyntese-medium" },
      { id: "pl_PL-bass-high" },
      { id: "pl_PL-darkman-medium" },
      { id: "pl_PL-gosia-medium" },
      { id: "pl_PL-mc_speech-medium" },
      { id: "pl_PL-mls_6892-low" },
      { id: "pt_BR-cadu-medium" },
      { id: "pt_BR-edresson-low" },
      { id: "pt_BR-faber-medium" },
      { id: "pt_BR-jeff-medium" },
      { id: "pt_PT-tugão-medium" },
      { id: "ro_RO-mihai-medium" },
      { id: "ru_RU-denis-medium" },
      { id: "ru_RU-dmitri-medium" },
      { id: "ru_RU-irina-medium" },
      { id: "ru_RU-ruslan-medium" },
      { id: "sk_SK-lili-medium" },
      { id: "sl_SI-artur-medium" },
      { id: "sr_RS-serbski_institut-medium" },
      { id: "sv_SE-alma-medium" },
      { id: "sv_SE-lisa-medium" },
      { id: "sv_SE-nst-medium" },
      { id: "sw_CD-lanfrica-medium" },
      { id: "te_IN-maya-medium" },
      { id: "te_IN-padmavathi-medium" },
      { id: "te_IN-venkatesh-medium" },
      { id: "tr_TR-dfki-medium" },
      { id: "uk_UA-lada-x_low" },
      { id: "uk_UA-ukrainian_tts-medium" },
      { id: "vi_VN-25hours_single-low" },
      { id: "vi_VN-vais1000-medium" },
      { id: "vi_VN-vivos-x_low" },
      { id: "zh_CN-chaowen-medium" },
      { id: "zh_CN-huayan-medium" },
      { id: "zh_CN-huayan-x_low" },
      { id: "zh_CN-xiao_ya-medium" },
    ],
  },
  "espeak-ng": {
    label: "eSpeak NG",
    voices: [
      { id: "en", label: "English" },
      { id: "en-us", label: "English (US)" },
      { id: "en-gb", label: "English (GB)" },
      { id: "ar", label: "Arabic" },
      { id: "bn", label: "Bengali" },
      { id: "cs", label: "Czech" },
      { id: "da", label: "Danish" },
      { id: "de", label: "German" },
      { id: "el", label: "Greek" },
      { id: "es", label: "Spanish" },
      { id: "fa", label: "Farsi" },
      { id: "fr", label: "French" },
      { id: "hi", label: "Hindi" },
      { id: "hy", label: "Armenian" },
      { id: "ja", label: "Japanese" },
      { id: "ko", label: "Korean" },
      { id: "nl", label: "Dutch" },
      { id: "no", label: "Norwegian" },
      { id: "pl", label: "Polish" },
      { id: "pt", label: "Portuguese" },
      { id: "ro", label: "Romanian" },
      { id: "ru", label: "Russian" },
      { id: "sv", label: "Swedish" },
      { id: "tr", label: "Turkish" },
      { id: "vi", label: "Vietnamese" },
      { id: "zh", label: "Chinese" },
    ],
  },
  macos: {
    label: "macOS",
    voices: [
      { id: "Albert" },
      { id: "Alice", label: "Alice (it-IT)" },
      { id: "Alva", label: "Alva (sv-SE)" },
      { id: "Aman", label: "Aman (en-IN)" },
      { id: "Amélie", label: "Amélie (fr-CA)" },
      { id: "Amira", label: "Amira (ms-MY)" },
      { id: "Anna", label: "Anna (de-DE)" },
      { id: "Aru", label: "Aru (kk-KZ)" },
      { id: "Bad News" },
      { id: "Bahh" },
      { id: "Bells" },
      { id: "Boing" },
      { id: "Bubbles" },
      { id: "Carmit", label: "Carmit (he-IL)" },
      { id: "Cellos" },
      { id: "Damayanti", label: "Damayanti (id-ID)" },
      { id: "Daniel", label: "Daniel (en-GB)" },
      { id: "Daria", label: "Daria (bg-BG)" },
      { id: "Ellen", label: "Ellen (nl-BE)" },
      { id: "Flo (English (UK))", label: "Flo (en-GB)" },
      { id: "Flo (English (US))", label: "Flo (en-US)" },
      { id: "Fred" },
      { id: "Geeta", label: "Geeta (te-IN)" },
      { id: "Good News" },
      { id: "Ioana", label: "Ioana (ro-RO)" },
      { id: "Jacques", label: "Jacques (fr-FR)" },
      { id: "Jester" },
      { id: "Joana", label: "Joana (pt-PT)" },
      { id: "Junior" },
      { id: "Kanya", label: "Kanya (th-TH)" },
      { id: "Karen", label: "Karen (en-AU)" },
      { id: "Kathy" },
      { id: "Kyoko", label: "Kyoko (ja-JP)" },
      { id: "Lana", label: "Lana (hr-HR)" },
      { id: "Laura", label: "Laura (sk-SK)" },
      { id: "Lekha", label: "Lekha (hi-IN)" },
      { id: "Lesya", label: "Lesya (uk-UA)" },
      { id: "Linh", label: "Linh (vi-VN)" },
      { id: "Luciana", label: "Luciana (pt-BR)" },
      { id: "Majed", label: "Majed (ar)" },
      { id: "Meijia", label: "Meijia (zh-TW)" },
      { id: "Melina", label: "Melina (el-GR)" },
      { id: "Milena", label: "Milena (ru-RU)" },
      { id: "Moira", label: "Moira (en-IE)" },
      { id: "Mónica", label: "Mónica (es-ES)" },
      { id: "Montse", label: "Montse (ca-ES)" },
      { id: "Nora", label: "Nora (nb-NO)" },
      { id: "Ona", label: "Ona (lt-LT)" },
      { id: "Organ" },
      { id: "Paulina", label: "Paulina (es-MX)" },
      { id: "Piya", label: "Piya (bn-IN)" },
      { id: "Ralph" },
      { id: "Rishi", label: "Rishi (en-IN)" },
      { id: "Samantha" },
      { id: "Sara", label: "Sara (da-DK)" },
      { id: "Satu", label: "Satu (fi-FI)" },
      { id: "Sinji", label: "Sinji (zh-HK)" },
      { id: "Soumya", label: "Soumya (kn-IN)" },
      { id: "Superstar" },
      { id: "Tara", label: "Tara (en-IN)" },
      { id: "Tessa", label: "Tessa (en-ZA)" },
      { id: "Thomas", label: "Thomas (fr-FR)" },
      { id: "Tina", label: "Tina (sl-SI)" },
      { id: "Tingting", label: "Tingting (zh-CN)" },
      { id: "Trinoids" },
      { id: "Tünde", label: "Tünde (hu-HU)" },
      { id: "Vani", label: "Vani (ta-IN)" },
      { id: "Whisper" },
      { id: "Wobble" },
      { id: "Xander", label: "Xander (nl-NL)" },
      { id: "Yelda", label: "Yelda (tr-TR)" },
      { id: "Yuna", label: "Yuna (ko-KR)" },
      { id: "Zarvox" },
      { id: "Zosia", label: "Zosia (pl-PL)" },
      { id: "Zuzana", label: "Zuzana (cs-CZ)" },
    ],
  },
};
